"""Generic criteria profile for a data science internship."""

from resume_pdf_agent.models import (
    CriteriaCategory,
    ResumeType,
    RoleCriteriaProfile,
    ScreeningCriterion,
    SourceMetadata,
    SourceType,
)

_SOURCE = SourceMetadata(
    source_type=SourceType.MANUALLY_CURATED,
    title="Generic public data science internship criteria",
    organization="resume_pdf_agent",
    notes=(
        "Manually curated from common public internship requirements. This is not "
        "an internal company screening standard."
    ),
)

SAMPLE_CRITERIA_PROFILE = RoleCriteriaProfile(
    profile_id="criteria_data_science_intern_v0",
    role_title="Data Science Intern",
    industry="Technology",
    seniority_level="Internship",
    target_companies=[],
    resume_types=[ResumeType.DATA_SCIENCE_RESUME, ResumeType.GENERAL_STUDENT_RESUME],
    criteria=[
        ScreeningCriterion(
            criterion_id="ds_python_data_analysis",
            category=CriteriaCategory.SKILL_COVERAGE,
            name="Python and data analysis skill coverage",
            description="Evidence of using Python and common data analysis libraries.",
            importance=5,
            evidence_required=["Python project", "Data analysis task"],
            keywords=["Python", "pandas", "NumPy"],
            positive_signals=["Clear tooling and data task description"],
            negative_signals=["Lists tools without project evidence"],
            source=_SOURCE,
            confidence=0.75,
        ),
        ScreeningCriterion(
            criterion_id="ds_sql_database_familiarity",
            category=CriteriaCategory.SKILL_COVERAGE,
            name="SQL or database familiarity",
            description="Evidence of querying, joining, or organizing structured data.",
            importance=4,
            evidence_required=["SQL coursework or project"],
            keywords=["SQL", "database", "query"],
            positive_signals=["Specific database task or coursework"],
            negative_signals=["Unsupported database expertise claim"],
            source=_SOURCE,
            confidence=0.7,
        ),
        ScreeningCriterion(
            criterion_id="ds_statistical_reasoning",
            category=CriteriaCategory.EDUCATION_RELEVANCE,
            name="Statistical reasoning",
            description="Evidence of probability, statistics, or modeling coursework.",
            importance=4,
            evidence_required=["Statistics coursework", "Modeling explanation"],
            keywords=["statistics", "regression", "hypothesis testing"],
            positive_signals=["Explains assumptions or model limitations"],
            negative_signals=["Mentions models without reasoning"],
            source=_SOURCE,
            confidence=0.75,
        ),
        ScreeningCriterion(
            criterion_id="ds_ml_project_evidence",
            category=CriteriaCategory.EVIDENCE_STRENGTH,
            name="Machine learning project evidence",
            description="Evidence of applied machine learning or baseline modeling work.",
            importance=4,
            evidence_required=["ML project", "Modeling method"],
            keywords=["machine learning", "scikit-learn", "model"],
            positive_signals=["Method, data, and result are connected"],
            negative_signals=["Broad ML claims without project detail"],
            source=_SOURCE,
            confidence=0.7,
        ),
        ScreeningCriterion(
            criterion_id="ds_data_cleaning_visualization",
            category=CriteriaCategory.SKILL_COVERAGE,
            name="Data cleaning and visualization",
            description="Evidence of preparing data and communicating findings.",
            importance=4,
            evidence_required=["Data cleaning task", "Visualization or report"],
            keywords=["data cleaning", "visualization", "Tableau", "Matplotlib"],
            positive_signals=["Data preparation and communication are both visible"],
            negative_signals=["Only lists tools with no task context"],
            source=_SOURCE,
            confidence=0.7,
        ),
        ScreeningCriterion(
            criterion_id="ds_action_result_clarity",
            category=CriteriaCategory.ACTION_RESULT_CLARITY,
            name="Action-result clarity",
            description="Resume bullets should connect actions to outcomes or deliverables.",
            importance=5,
            evidence_required=["Action", "Outcome or deliverable"],
            keywords=["built", "analyzed", "presented", "documented"],
            positive_signals=["Clear action and result relationship"],
            negative_signals=["Vague responsibility-only bullet"],
            source=_SOURCE,
            confidence=0.8,
        ),
        ScreeningCriterion(
            criterion_id="ds_measurable_impact_when_provided",
            category=CriteriaCategory.IMPACT_QUANTIFICATION,
            name="Measurable impact when user-provided",
            description="Use metrics only when the user provides evidence for them.",
            importance=3,
            evidence_required=["User-provided metric or source note"],
            keywords=["measured", "evaluated", "reported"],
            positive_signals=["Metric includes context and source"],
            negative_signals=["Invented percentage or unsupported impact claim"],
            source=_SOURCE,
            confidence=0.8,
        ),
        ScreeningCriterion(
            criterion_id="ds_ats_readability",
            category=CriteriaCategory.ATS_READABILITY,
            name="ATS readability",
            description="Use clear headings, standard terms, and readable text structure.",
            importance=4,
            evidence_required=["Standard section headings", "Relevant keywords"],
            keywords=["Python", "SQL", "statistics", "project"],
            positive_signals=["Readable section structure"],
            negative_signals=["Overly decorative or unclear wording"],
            source=_SOURCE,
            confidence=0.75,
        ),
        ScreeningCriterion(
            criterion_id="ds_truthfulness_risk",
            category=CriteriaCategory.TRUTHFULNESS_RISK,
            name="Truthfulness risk",
            description="Claims should be traceable to user-provided evidence.",
            importance=5,
            evidence_required=["Evidence note", "User confirmation when uncertain"],
            keywords=["confirmed", "evidence", "source"],
            positive_signals=["Unsupported claims are flagged for confirmation"],
            negative_signals=["Internal standard claims or fabricated achievements"],
            source=_SOURCE,
            confidence=0.8,
        ),
    ],
    notes=(
        "Sample criteria are generic and manually curated for schema testing. "
        "They do not represent private, confidential, or company-specific rules."
    ),
)
