"""Rule definitions for deterministic resume type classification."""

from resume_pdf_agent.models import ResumeType

SOURCE_WEIGHTS: dict[str, float] = {
    "target_role": 5.0,
    "selected_criteria_profile": 4.0,
    "experience_type": 3.0,
    "experience_title": 3.0,
    "skill": 2.5,
    "skill_category": 2.0,
    "major": 2.0,
    "core_course": 1.5,
    "target_industry": 1.5,
    "target_company": 1.0,
    "award": 1.0,
    "additional_text": 1.0,
}

RESUME_TYPE_KEYWORDS: dict[ResumeType, list[str]] = {
    ResumeType.DATA_SCIENCE_RESUME: [
        "data science",
        "data scientist",
        "data analyst",
        "machine learning",
        "statistics",
        "probability",
        "python",
        " r ",
        "sql",
        "pandas",
        "numpy",
        "scikit learn",
        "model evaluation",
        "visualization",
        "regression",
        "classification",
        "data cleaning",
    ],
    ResumeType.TECHNICAL_RESUME: [
        "software engineer",
        "software engineering",
        "backend",
        "frontend",
        "full stack",
        "algorithm",
        "data structures",
        "git",
        "api",
        "testing",
        "debugging",
        "docker",
        "java",
        "c++",
        "javascript",
        "typescript",
        "react",
    ],
    ResumeType.FINANCE_BUSINESS_RESUME: [
        "finance",
        "investment",
        "valuation",
        "accounting",
        "financial modeling",
        "excel",
        "market research",
        "corporate finance",
        "equity research",
        "due diligence",
    ],
    ResumeType.CONSULTING_RESUME: [
        "consulting",
        "strategy",
        "case",
        "market sizing",
        "business analysis",
        "stakeholder",
        "presentation",
        "structured problem solving",
        "hypothesis driven",
        "hypothesis-driven",
        "client",
    ],
    ResumeType.RESEARCH_CV: [
        "research",
        "research assistant",
        "literature review",
        "lab",
        "experiment",
        "modeling",
        "publication",
        "manuscript",
        "professor",
        "academic writing",
        "reproducibility",
    ],
    ResumeType.PRODUCT_MANAGER_RESUME: [
        "product manager",
        "product management",
        "product",
        "user research",
        "prd",
        "requirement",
        "prototype",
        "mvp",
        "roadmap",
        "prioritization",
        "user needs",
        "competitor analysis",
        "metrics",
    ],
    ResumeType.DESIGN_PORTFOLIO_RESUME: [
        "design",
        "portfolio",
        "ux",
        "ui",
        "visual design",
        "figma",
        "user interface",
        "interaction design",
        "typography",
        "brand",
        "illustration",
    ],
    ResumeType.GENERAL_STUDENT_RESUME: [
        "internship",
        "student",
        "campus",
        "leadership",
        "volunteer",
        "coursework",
        "competition",
        "general",
    ],
}

RECOMMENDED_SECTIONS: dict[ResumeType, list[str]] = {
    ResumeType.DATA_SCIENCE_RESUME: ["Education", "Technical Skills", "Projects", "Research or Experience"],
    ResumeType.TECHNICAL_RESUME: ["Education", "Technical Skills", "Software Projects", "Experience"],
    ResumeType.FINANCE_BUSINESS_RESUME: ["Education", "Finance Skills", "Projects", "Experience"],
    ResumeType.CONSULTING_RESUME: ["Education", "Experience", "Leadership", "Projects"],
    ResumeType.RESEARCH_CV: ["Education", "Research Experience", "Publications or Presentations", "Skills"],
    ResumeType.PRODUCT_MANAGER_RESUME: ["Education", "Product Experience", "Projects", "Skills"],
    ResumeType.DESIGN_PORTFOLIO_RESUME: ["Education", "Portfolio", "Design Projects", "Skills"],
    ResumeType.GENERAL_STUDENT_RESUME: ["Education", "Experience", "Projects", "Skills"],
}
