"""Models for M23 LLM review decision summaries."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, model_validator


class LLMReviewDecisionAction(str, Enum):
    """Supported decision actions generated by the M22 browser UI."""

    APPROVE_CANDIDATE = "approve_candidate"
    REJECT_CANDIDATE = "reject_candidate"
    NEEDS_EDITING = "needs_editing"
    PROVIDE_NOTE = "provide_note"
    IGNORE_FOR_NOW = "ignore_for_now"


_ACTION_ALIASES: dict[str, LLMReviewDecisionAction] = {
    "approve": LLMReviewDecisionAction.APPROVE_CANDIDATE,
    "approved": LLMReviewDecisionAction.APPROVE_CANDIDATE,
    "approve_candidate": LLMReviewDecisionAction.APPROVE_CANDIDATE,
    "reject": LLMReviewDecisionAction.REJECT_CANDIDATE,
    "rejected": LLMReviewDecisionAction.REJECT_CANDIDATE,
    "reject_candidate": LLMReviewDecisionAction.REJECT_CANDIDATE,
    "needs_edit": LLMReviewDecisionAction.NEEDS_EDITING,
    "needs_editing": LLMReviewDecisionAction.NEEDS_EDITING,
    "edit": LLMReviewDecisionAction.NEEDS_EDITING,
    "note": LLMReviewDecisionAction.PROVIDE_NOTE,
    "provide_note": LLMReviewDecisionAction.PROVIDE_NOTE,
    "ignore": LLMReviewDecisionAction.IGNORE_FOR_NOW,
    "ignored": LLMReviewDecisionAction.IGNORE_FOR_NOW,
    "ignore_for_now": LLMReviewDecisionAction.IGNORE_FOR_NOW,
}


def normalize_llm_review_decision_action(value: str) -> LLMReviewDecisionAction | None:
    """Return a normalized M22 decision action, or None for unknown actions."""

    return _ACTION_ALIASES.get(value.strip().lower())


class LLMReviewDecision(BaseModel):
    """A single advisory decision for an LLM rewrite candidate."""

    candidate_id: str = Field(min_length=1)
    action: str = Field(min_length=1)
    note: str | None = None
    replacement_text: str | None = None
    reviewed_at: str | None = None
    reviewer: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _accept_browser_export_shape(cls, raw: Any) -> Any:
        if not isinstance(raw, dict):
            return raw
        data = dict(raw)
        metadata = dict(data.get("metadata") or {})
        if "action" not in data and "decision" in data:
            data["action"] = data["decision"]
        if "note" not in data:
            data["note"] = data.get("reviewer_note") or data.get("user_note")
        if "reviewer" not in data and "reviewer_name" in data:
            data["reviewer"] = data["reviewer_name"]
        known = {
            "candidate_id",
            "action",
            "decision",
            "note",
            "reviewer_note",
            "user_note",
            "replacement_text",
            "reviewed_at",
            "reviewer",
            "reviewer_name",
            "metadata",
        }
        for key, value in raw.items():
            if key not in known:
                metadata[key] = value
        data["metadata"] = metadata
        return data

    @property
    def normalized_action(self) -> LLMReviewDecisionAction | None:
        return normalize_llm_review_decision_action(self.action)

    @property
    def has_note(self) -> bool:
        return bool((self.note or "").strip())


class LLMReviewDecisionFile(BaseModel):
    """A loaded llm_rewrite_review_decisions.json file."""

    decisions: list[LLMReviewDecision] = Field(default_factory=list)
    source: str | None = None
    generated_at: str | None = None
    schema_version: str | None = None
    reviewer_name: str | None = None
    reviewed_at: str | None = None
    notes: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _accept_list_or_browser_export_shape(cls, raw: Any) -> Any:
        if isinstance(raw, list):
            return {"decisions": raw}
        if not isinstance(raw, dict):
            return raw
        data = dict(raw)
        metadata = dict(data.get("metadata") or {})
        if "generated_at" not in data and "reviewed_at" in data:
            data["generated_at"] = data["reviewed_at"]
        known = {
            "decisions",
            "source",
            "generated_at",
            "schema_version",
            "reviewer_name",
            "reviewed_at",
            "notes",
            "metadata",
        }
        for key, value in raw.items():
            if key not in known:
                metadata[key] = value
        data["metadata"] = metadata
        return data

    @model_validator(mode="after")
    def _propagate_file_reviewer_fields(self) -> LLMReviewDecisionFile:
        for decision in self.decisions:
            if decision.reviewer is None:
                decision.reviewer = self.reviewer_name
            if decision.reviewed_at is None:
                decision.reviewed_at = self.reviewed_at
        return self


class LLMReviewCandidateDecisionSummary(BaseModel):
    """Decision summary for one candidate or one decision row."""

    candidate_id: str
    action: str | None = None
    normalized_action: str | None = None
    known_candidate: bool = True
    duplicate: bool = False
    has_note: bool = False
    note: str | None = None
    replacement_text: str | None = None


class LLMReviewDecisionSummary(BaseModel):
    """Deterministic advisory summary of LLM review decisions."""

    total_candidates: int = Field(ge=0, default=0)
    total_decisions: int = Field(ge=0, default=0)
    approved_count: int = Field(ge=0, default=0)
    rejected_count: int = Field(ge=0, default=0)
    needs_edit_count: int = Field(ge=0, default=0)
    note_count: int = Field(ge=0, default=0)
    ignored_count: int = Field(ge=0, default=0)
    approved_candidate_ids: list[str] = Field(default_factory=list)
    rejected_candidate_ids: list[str] = Field(default_factory=list)
    needs_edit_candidate_ids: list[str] = Field(default_factory=list)
    note_candidate_ids: list[str] = Field(default_factory=list)
    ignored_candidate_ids: list[str] = Field(default_factory=list)
    undecided_candidate_ids: list[str] = Field(default_factory=list)
    unknown_candidate_ids: list[str] = Field(default_factory=list)
    duplicate_candidate_ids: list[str] = Field(default_factory=list)
    invalid_decisions: list[str] = Field(default_factory=list)
    candidate_summaries: list[LLMReviewCandidateDecisionSummary] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    safety_notice: str = Field(min_length=1)
    result_path: str | None = None
    decisions_path: str | None = None
    summary: str = Field(min_length=1)
